"""Process-local cache for Monte Carlo evidence from planner runs.

The cache deliberately keeps raw simulation histories off the API surface.
It is an optimization layer: durable account state remains in the repository,
while simulation evidence is disposable and can be regenerated by Run Planner.
"""

from dataclasses import dataclass, replace
import threading

from domain import Goal
from optimizer.evaluation import CandidateStrategy
from simulation import SimulationResult, condition_on_pull


@dataclass(frozen=True)
class CachedSimulationEvidence:
    """Simulation evidence retained for one planner decision."""

    account_id: str
    goal: Goal
    result: SimulationResult
    runs: int
    seed: int | None
    confidence: float
    income_scenario: str
    observations: tuple[tuple[str, str, int], ...] = ()


@dataclass(frozen=True)
class CachedCandidateEvidence:
    """Recommendation candidate simulation retained for deterministic refresh."""

    account_id: str
    character: str
    constellation: int
    banner_version: str
    banner_phase: int
    budget: int
    candidate: CandidateStrategy
    runs: int
    seed: int | None
    observations: tuple[tuple[str, str, int], ...] = ()


class PlannerEvidenceCache:
    """Small process-local cache of the latest evidence per account/goal."""

    def __init__(self, max_entries: int = 32) -> None:
        if max_entries < 1:
            raise ValueError("max_entries must be >= 1")
        self._max_entries = max_entries
        self._entries: dict[tuple[str, Goal], CachedSimulationEvidence] = {}
        self._candidates: dict[tuple[str, str, int, str, int, int], CachedCandidateEvidence] = {}
        self._lock = threading.Lock()

    def put(
        self,
        account_id: str,
        goal: Goal,
        result: SimulationResult,
        *,
        runs: int,
        seed: int | None,
        confidence: float,
        income_scenario: str,
        observations: tuple[tuple[str, str, int], ...] = (),
    ) -> None:
        evidence = CachedSimulationEvidence(
            account_id=account_id,
            goal=goal,
            result=result,
            runs=runs,
            seed=seed,
            confidence=confidence,
            income_scenario=income_scenario,
            observations=observations,
        )
        key = (account_id, goal)
        with self._lock:
            self._entries[key] = evidence
            while len(self._entries) > self._max_entries:
                self._entries.pop(next(iter(self._entries)))

    def get(self, account_id: str, goal: Goal) -> CachedSimulationEvidence | None:
        with self._lock:
            return self._entries.get((account_id, goal))

    def condition_account(
        self,
        account_id: str,
        *,
        character: str,
        outcome: str,
        wishes_used: int,
    ) -> dict[Goal, CachedSimulationEvidence]:
        """Condition cached evidence and replace it with the observed state."""
        with self._lock:
            entries = tuple(
                evidence
                for (cached_account_id, _), evidence in self._entries.items()
                if cached_account_id == account_id
            )

        conditioned: dict[Goal, CachedSimulationEvidence] = {}
        for evidence in entries:
            result = condition_on_pull(
                evidence.result,
                character=character,
                outcome=outcome,
                wishes_used=wishes_used,
                prior_observations=evidence.observations,
            )
            key = (account_id, evidence.goal)
            if result is None:
                # Keep the original evidence available to the caller. Rare
                # observations need a targeted resimulation rather than
                # destroying the only reusable evidence.
                continue

            updated = CachedSimulationEvidence(
                account_id=evidence.account_id,
                goal=evidence.goal,
                result=result,
                runs=result.runs,
                seed=evidence.seed,
                confidence=evidence.confidence,
                income_scenario=evidence.income_scenario,
                observations=(
                    *evidence.observations,
                    (character, outcome, wishes_used),
                ),
            )
            with self._lock:
                self._entries[key] = updated
            conditioned[evidence.goal] = updated

        return conditioned

    def put_candidate(
        self,
        account_id: str,
        candidate: CandidateStrategy,
        *,
        runs: int,
        seed: int | None,
    ) -> None:
        banner = candidate.plan.entries[0].banner
        evidence = CachedCandidateEvidence(
            account_id=account_id,
            character=candidate.outcome.character,
            constellation=candidate.outcome.constellation,
            banner_version=banner.version,
            banner_phase=banner.phase,
            budget=candidate.budget,
            candidate=candidate,
            runs=runs,
            seed=seed,
        )
        key = (
            account_id,
            candidate.outcome.character,
            candidate.outcome.constellation,
            banner.version,
            banner.phase,
            candidate.budget,
        )
        with self._lock:
            self._candidates[key] = evidence
            while len(self._candidates) > self._max_entries * 8:
                self._candidates.pop(next(iter(self._candidates)))

    def condition_candidate(
        self,
        account_id: str,
        *,
        character: str,
        outcome: str,
        constellation: int,
        banner_version: str,
        banner_phase: int,
        new_budget: int,
        wishes_used: int,
    ) -> CachedCandidateEvidence | None:
        old_budget = new_budget + wishes_used
        key = (account_id, character, constellation, banner_version, banner_phase, old_budget)
        with self._lock:
            evidence = self._candidates.get(key)
        if evidence is None:
            return None

        conditioned = condition_on_pull(
            evidence.candidate.result,
            character=character,
            outcome=outcome,
            wishes_used=wishes_used,
            prior_observations=evidence.observations,
        )
        if conditioned is None:
            return None

        candidate = replace(
            evidence.candidate,
            budget=new_budget,
            result=conditioned,
            outcome_probability=conditioned.banners[0].target_met_probability,
        )
        updated = CachedCandidateEvidence(
            account_id=evidence.account_id,
            character=evidence.character,
            constellation=evidence.constellation,
            banner_version=evidence.banner_version,
            banner_phase=evidence.banner_phase,
            budget=new_budget,
            candidate=candidate,
            runs=conditioned.runs,
            seed=evidence.seed,
            observations=(*evidence.observations, (character, outcome, wishes_used)),
        )
        new_key = (account_id, character, constellation, banner_version, banner_phase, new_budget)
        with self._lock:
            self._candidates.pop(key, None)
            self._candidates[new_key] = updated
        return updated

    def clear_account(self, account_id: str) -> None:
        with self._lock:
            for key in tuple(self._entries):
                if key[0] == account_id:
                    del self._entries[key]
            for key in tuple(self._candidates):
                if key[0] == account_id:
                    del self._candidates[key]

    def clear(self) -> None:
        with self._lock:
            self._entries.clear()
            self._candidates.clear()


planner_evidence_cache = PlannerEvidenceCache()
