"""Process-local cache for Monte Carlo evidence from planner runs.

The cache deliberately keeps raw simulation histories off the API surface.
It is an optimization layer: durable account state remains in the repository,
while simulation evidence is disposable and can be regenerated by Run Planner.

Staleness (fingerprinting)
--------------------------
Every cache entry is written with a fingerprint of the parts of
PlannerContext that affect simulated probabilities: confidence, income
scenario, mechanics, the income forecast itself, the roadmap's goals and
banners, and the current version/phase. It deliberately EXCLUDES the
account's own pity/guarantee/wishes/ownership, because those are expected
to move on every recorded pull - that movement is exactly what
condition_account/condition_candidate are for.

Every read and every conditioning call takes the caller's current context and
requires the same fingerprint. A mismatch is treated like a cache miss.
"""

from dataclasses import dataclass, replace
import threading

from domain import Banner, Goal
from optimizer.evaluation import CandidateStrategy, GoalStanding, SkipBaseline
from planner.context import PlannerContext
from simulation import SimulationResult, condition_on_pull


def _mechanics_signature(mechanics) -> tuple:
    return (
        mechanics.banner_type,
        mechanics.hard_pity,
        mechanics.soft_pity_start,
        mechanics.base_rate,
        mechanics.soft_pity_increment,
        mechanics.featured_rate,
    )


def _income_signature(income) -> tuple | None:
    if income is None:
        return None
    return tuple(sorted((
        entry.version,
        entry.aggregate.low,
        entry.aggregate.expected,
        entry.aggregate.high,
    ) for entry in income.versions))


def context_fingerprint(context: PlannerContext) -> tuple:
    roadmap = context.roadmap
    return (
        context.current_version,
        context.current_phase,
        context.confidence,
        context.income_scenario,
        _mechanics_signature(context.mechanics),
        _income_signature(context.income),
        tuple(sorted((goal.character, goal.constellation, goal.priority) for goal in roadmap.goals)),
        tuple(sorted((banner.character, banner.version, banner.phase) for banner in roadmap.banners)),
    )


@dataclass(frozen=True)
class CachedSimulationEvidence:
    account_id: str
    goal: Goal
    result: SimulationResult
    runs: int
    seed: int | None
    confidence: float
    income_scenario: str
    fingerprint: tuple
    observations: tuple[tuple[str, str, int], ...] = ()


@dataclass(frozen=True)
class CachedCandidateEvidence:
    account_id: str
    character: str
    constellation: int
    banner_version: str
    banner_phase: int
    budget: int
    candidate: CandidateStrategy
    runs: int
    seed: int | None
    fingerprint: tuple
    observations: tuple[tuple[str, str, int], ...] = ()


class PlannerEvidenceCache:
    def __init__(self, max_entries: int = 32) -> None:
        if max_entries < 1:
            raise ValueError("max_entries must be >= 1")
        self._max_entries = max_entries
        self._entries: dict[tuple[str, Goal], CachedSimulationEvidence] = {}
        self._candidates: dict[tuple[str, str, int, str, int, int], CachedCandidateEvidence] = {}
        self._skip_baselines: dict[tuple[str, str, int], tuple[SkipBaseline, tuple]] = {}
        self._lock = threading.Lock()

    def put(self, account_id, goal, result, *, runs, seed, confidence, income_scenario, context, observations=()):
        evidence = CachedSimulationEvidence(account_id, goal, result, runs, seed, confidence, income_scenario, context_fingerprint(context), observations)
        key = (account_id, goal)
        with self._lock:
            self._entries[key] = evidence
            while len(self._entries) > self._max_entries:
                self._entries.pop(next(iter(self._entries)))

    def get(self, account_id, goal, *, context=None):
        with self._lock:
            evidence = self._entries.get((account_id, goal))
        if evidence is None or (context is not None and evidence.fingerprint != context_fingerprint(context)):
            return None
        return evidence

    def condition_account(self, account_id, *, character, outcome, wishes_used, context=None):
        expected_fingerprint = None if context is None else context_fingerprint(context)
        with self._lock:
            entries = tuple(e for (aid, _), e in self._entries.items() if aid == account_id)
        conditioned = {}
        for evidence in entries:
            if expected_fingerprint is not None and evidence.fingerprint != expected_fingerprint:
                continue
            result = condition_on_pull(evidence.result, character=character, outcome=outcome, wishes_used=wishes_used, prior_observations=evidence.observations)
            if result is None:
                continue
            updated = CachedSimulationEvidence(
                account_id=evidence.account_id, goal=evidence.goal, result=result,
                runs=result.runs, seed=evidence.seed, confidence=evidence.confidence,
                income_scenario=evidence.income_scenario, fingerprint=evidence.fingerprint,
                observations=(*evidence.observations, (character, outcome, wishes_used)),
            )
            with self._lock:
                self._entries[(account_id, evidence.goal)] = updated
            conditioned[evidence.goal] = updated
        return conditioned

    def put_candidate(self, account_id, candidate, *, runs, seed, context):
        banner = candidate.plan.entries[0].banner
        evidence = CachedCandidateEvidence(
            account_id, candidate.outcome.character, candidate.outcome.constellation,
            banner.version, banner.phase, candidate.budget, candidate, runs, seed,
            context_fingerprint(context),
        )
        key = (account_id, candidate.outcome.character, candidate.outcome.constellation, banner.version, banner.phase, candidate.budget)
        with self._lock:
            self._candidates[key] = evidence
            while len(self._candidates) > self._max_entries * 8:
                self._candidates.pop(next(iter(self._candidates)))

    def get_candidate(self, account_id, *, character, constellation, banner_version, banner_phase, budget, context=None):
        key = (account_id, character, constellation, banner_version, banner_phase, budget)
        with self._lock:
            evidence = self._candidates.get(key)
        if evidence is None or (context is not None and evidence.fingerprint != context_fingerprint(context)):
            return None
        return evidence

    def condition_candidate(self, account_id, *, character, outcome, constellation, banner_version, banner_phase, new_budget, wishes_used, context=None):
        old_budget = new_budget + wishes_used
        key = (account_id, character, constellation, banner_version, banner_phase, old_budget)
        with self._lock:
            evidence = self._candidates.get(key)
        if evidence is None or (context is not None and evidence.fingerprint != context_fingerprint(context)):
            return None
        conditioned = condition_on_pull(evidence.candidate.result, character=character, outcome=outcome, wishes_used=wishes_used, prior_observations=evidence.observations)
        if conditioned is None:
            return None
        candidate = replace(evidence.candidate, budget=new_budget, result=conditioned, outcome_probability=conditioned.banners[0].target_met_probability)
        updated = CachedCandidateEvidence(
            account_id=evidence.account_id, character=evidence.character, constellation=evidence.constellation,
            banner_version=evidence.banner_version, banner_phase=evidence.banner_phase, budget=new_budget,
            candidate=candidate, runs=conditioned.runs, seed=evidence.seed, fingerprint=evidence.fingerprint,
            observations=(*evidence.observations, (character, outcome, wishes_used)),
        )
        new_key = (account_id, character, constellation, banner_version, banner_phase, new_budget)
        with self._lock:
            self._candidates.pop(key, None)
            self._candidates[new_key] = updated
        return updated

    def clear_account(self, account_id):
        with self._lock:
            for key in tuple(self._entries):
                if key[0] == account_id: del self._entries[key]
            for key in tuple(self._candidates):
                if key[0] == account_id: del self._candidates[key]
            for key in tuple(self._skip_baselines):
                if key[0] == account_id: del self._skip_baselines[key]

    def clear(self):
        with self._lock:
            self._entries.clear(); self._candidates.clear(); self._skip_baselines.clear()

    def get_skip_baseline(self, account_id, banner, *, context):
        key = (account_id, banner.version, banner.phase)
        with self._lock:
            entry = self._skip_baselines.get(key)
        if entry is None:
            return None
        baseline, fingerprint = entry
        if fingerprint != context_fingerprint(context):
            return None
        return baseline.protected if isinstance(baseline, SkipBaseline) else baseline

    def get_skip_baseline_full(self, account_id, banner, *, context):
        key = (account_id, banner.version, banner.phase)
        with self._lock:
            entry = self._skip_baselines.get(key)
        if entry is None:
            return None
        baseline, fingerprint = entry
        if fingerprint != context_fingerprint(context):
            return None
        return baseline

    def put_skip_baseline(self, account_id, banner, baseline, *, context):
        key = (account_id, banner.version, banner.phase)
        with self._lock:
            self._skip_baselines[key] = (baseline, context_fingerprint(context))
            while len(self._skip_baselines) > self._max_entries:
                self._skip_baselines.pop(next(iter(self._skip_baselines)))


planner_evidence_cache = PlannerEvidenceCache()
