"""Process-local cache for Monte Carlo evidence from planner runs.

The cache deliberately keeps raw simulation histories off the API surface.
It is an optimization layer: durable account state remains in the repository,
while simulation evidence is disposable and can be regenerated by Run Planner.
"""

from dataclasses import dataclass
import threading

from domain import Goal
from simulation import SimulationResult, condition_on_pull


@dataclass(frozen=True)
class CachedSimulationEvidence:
    """Simulation evidence retained for one planner decision."""

    account_id: str
    goal: Goal
    result: SimulationResult
    runs: int
    seed: int | None
    confidence: float
    income_scenario: str


class PlannerEvidenceCache:
    """Small process-local cache of the latest evidence per account/goal."""

    def __init__(self, max_entries: int = 32) -> None:
        if max_entries < 1:
            raise ValueError("max_entries must be >= 1")
        self._max_entries = max_entries
        self._entries: dict[tuple[str, Goal], CachedSimulationEvidence] = {}
        self._lock = threading.Lock()

    def put(
        self,
        account_id: str,
        goal: Goal,
        result: SimulationResult,
        *,
        runs: int,
        seed: int | None,
        confidence: float,
        income_scenario: str,
    ) -> None:
        evidence = CachedSimulationEvidence(
            account_id=account_id,
            goal=goal,
            result=result,
            runs=runs,
            seed=seed,
            confidence=confidence,
            income_scenario=income_scenario,
        )
        key = (account_id, goal)
        with self._lock:
            self._entries[key] = evidence
            while len(self._entries) > self._max_entries:
                self._entries.pop(next(iter(self._entries)))

    def get(self, account_id: str, goal: Goal) -> CachedSimulationEvidence | None:
        with self._lock:
            return self._entries.get((account_id, goal))

    def condition_account(
        self,
        account_id: str,
        *,
        character: str,
        outcome: str,
        wishes_used: int,
    ) -> dict[Goal, CachedSimulationEvidence]:
        """Condition every cached goal for an account on one observed pull."""
        with self._lock:
            entries = tuple(
                evidence
                for (cached_account_id, _), evidence in self._entries.items()
                if cached_account_id == account_id
            )

        conditioned: dict[Goal, CachedSimulationEvidence] = {}
        for evidence in entries:
            result = condition_on_pull(
                evidence.result,
                character=character,
                outcome=outcome,
                wishes_used=wishes_used,
            )
            if result is None:
                continue
            conditioned[evidence.goal] = CachedSimulationEvidence(
                account_id=evidence.account_id,
                goal=evidence.goal,
                result=result,
                runs=result.runs,
                seed=evidence.seed,
                confidence=evidence.confidence,
                income_scenario=evidence.income_scenario,
            )
        return conditioned

    def clear_account(self, account_id: str) -> None:
        with self._lock:
            for key in tuple(self._entries):
                if key[0] == account_id:
                    del self._entries[key]

    def clear(self) -> None:
        with self._lock:
            self._entries.clear()


planner_evidence_cache = PlannerEvidenceCache()
